In [1]:
import pandas as pd

In [2]:
#Check the version of Pandas
pd.__version__

'1.4.2'

In [3]:
#Install new package in order to read .xml file
!pip install pandas_read_xml

Requirement already satisfied: pandas_read_xml in /opt/anaconda3/lib/python3.9/site-packages (0.3.1)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (2.27.1)
Requirement already satisfied: zipfile36 in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (0.1.3)
Requirement already satisfied: xmltodict in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (0.13.0)
Requirement already satisfied: urllib3>=1.26.3 in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (1.26.9)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (1.4.2)
Requirement already satisfied: distlib in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (0.3.4)
Requirement already satisfied: pyarrow in /opt/anaconda3/lib/python3.9/site-packages (from pandas_read_xml) (8.0.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas->pandas_read_xml) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas->pandas_read_xml) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in /opt/anaconda3/lib/python3.9/site-packages (from pandas->pandas_read_xml) (1.21.5)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas->pandas_read_xml) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.9/site-packages (from requests->pandas_read_xml) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from requests->pandas_read_xml) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.9/site-packages (from requests->pandas_read_xml) (3.3)

In [4]:
import pandas_read_xml as pdx
from pandas_read_xml import fully_flatten

In [5]:
#Orphadata: Free access data from Orphanet. 
#© INSERM 1999. Available on http://www.orphadata.org. Data version (XML data version).
#Dataset (.xml file) from http://www.orphadata.org/cgi-bin/epidemio.html
#Latest date of update for the dataset: 7/6/2022
#Creative Commons Attribution 4.0 International

#Read .xml file
df = pdx.read_xml('http://www.orphadata.org/data/xml/en_product9_ages.xml').pipe(fully_flatten)
df.head()

,JDBOR|@copyright,JDBOR|@date,JDBOR|@dbserver,JDBOR|@version,JDBOR|Availability|Licence|FullName,JDBOR|Availability|Licence|FullName|@lang,JDBOR|Availability|Licence|LegalCode,JDBOR|Availability|Licence|ShortIdentifier,JDBOR|DisorderList|@count,JDBOR|DisorderList|Disorder|@id,...,JDBOR|DisorderList|Disorder|DisorderType|Name|@lang,JDBOR|DisorderList|Disorder|ExpertLink,JDBOR|DisorderList|Disorder|ExpertLink|@lang,JDBOR|DisorderList|Disorder|Name,JDBOR|DisorderList|Disorder|Name|@lang,JDBOR|DisorderList|Disorder|OrphaCode,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name|@lang
0,Orphanet (c) 2022,2022-06-14 16:29:20,jdbc:sybase:Tds:canard.orpha.net:2020,1.3.16 / 4.1.7 [2022-01-26] (orientdb version),Creative Commons Attribution 4.0 International,en,https://creativecommons.org/licenses/by/4.0/le...,CC-BY-4.0,6636,44,...,en,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,en,Turner syndrome,en,881,2,23494,Not applicable,en
1,Orphanet (c) 2022,2022-06-14 16:29:20,jdbc:sybase:Tds:canard.orpha.net:2020,1.3.16 / 4.1.7 [2022-01-26] (orientdb version),Creative Commons Attribution 4.0 International,en,https://creativecommons.org/licenses/by/4.0/le...,CC-BY-4.0,6636,44,...,en,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,en,Turner syndrome,en,881,2,23480,Unknown,en
2,Orphanet (c) 2022,2022-06-14 16:29:20,jdbc:sybase:Tds:canard.orpha.net:2020,1.3.16 / 4.1.7 [2022-01-26] (orientdb version),Creative Commons Attribution 4.0 International,en,https://creativecommons.org/licenses/by/4.0/le...,CC-BY-4.0,6636,44,...,en,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,en,Turner syndrome,en,881,2,23494,Not applicable,en
3,Orphanet (c) 2022,2022-06-14 16:29:20,jdbc:sybase:Tds:canard.orpha.net:2020,1.3.16 / 4.1.7 [2022-01-26] (orientdb version),Creative Commons Attribution 4.0 International,en,https://creativecommons.org/licenses/by/4.0/le...,CC-BY-4.0,6636,44,...,en,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,en,Turner syndrome,en,881,2,23480,Unknown,en
4,Orphanet (c) 2022,2022-06-14 16:29:20,jdbc:sybase:Tds:canard.orpha.net:2020,1.3.16 / 4.1.7 [2022-01-26] (orientdb version),Creative Commons Attribution 4.0 International,en,https://creativecommons.org/licenses/by/4.0/le...,CC-BY-4.0,6636,44,...,en,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,en,Turner syndrome,en,881,2,23494,Not applicable,en

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14591 entries, 0 to 14590
Data columns (total 33 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   JDBOR|@copyright                                                                14591 non-null  object
 1   JDBOR|@date                                                                     14591 non-null  object
 2   JDBOR|@dbserver                                                                 14591 non-null  object
 3   JDBOR|@version                                                                  14591 non-null  object
 4   JDBOR|Availability|Licence|FullName                                             14591 non-null  object
 5   JDBOR|Availability|Licence|FullName|@lang                                       14591 non-null  object
 6   JDBOR|Availability|Licence|LegalCode                                            14591 non-null  object
 7   JDBOR|Availability|Licence|ShortIdentifier                                      14591 non-null  object
 8   JDBOR|DisorderList|@count                                                       14591 non-null  object
 9   JDBOR|DisorderList|Disorder|@id                                                 14591 non-null  object
 10  JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|@count                        14591 non-null  object
 11  JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|@id         9312 non-null   object
 12  JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name        9312 non-null   object
 13  JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name|@lang  9312 non-null   object
 14  JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|@count                        14591 non-null  object
 15  JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|@id         14139 non-null  object
 16  JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name        14139 non-null  object
 17  JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name|@lang  14139 non-null  object
 18  JDBOR|DisorderList|Disorder|DisorderGroup|@id                                   14591 non-null  object
 19  JDBOR|DisorderList|Disorder|DisorderGroup|Name                                  14591 non-null  object
 20  JDBOR|DisorderList|Disorder|DisorderGroup|Name|@lang                            14591 non-null  object
 21  JDBOR|DisorderList|Disorder|DisorderType|@id                                    14591 non-null  object
 22  JDBOR|DisorderList|Disorder|DisorderType|Name                                   14591 non-null  object
 23  JDBOR|DisorderList|Disorder|DisorderType|Name|@lang                             14591 non-null  object
 24  JDBOR|DisorderList|Disorder|ExpertLink                                          14591 non-null  object
 25  JDBOR|DisorderList|Disorder|ExpertLink|@lang                                    14591 non-null  object
 26  JDBOR|DisorderList|Disorder|Name                                                14591 non-null  object
 27  JDBOR|DisorderList|Disorder|Name|@lang                                          14591 non-null  object
 28  JDBOR|DisorderList|Disorder|OrphaCode                                           14591 non-null  object
 29  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count                        14591 non-null  object
 30  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id         12433 non-null  object
 31  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name        12433 non-null  object
 32  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name|@lang  12433 non-null  object
dtypes: object(33)
memory usage: 3.7+ MB

In [7]:
#Dropping columns that are not required for data analysis at this stage
df.drop(columns = ['JDBOR|@date', 
                   'JDBOR|@copyright', 
                   'JDBOR|Availability|Licence|FullName|@lang'], 
        inplace = True)

#Continue to drop further columns not required
df.drop(['JDBOR|@dbserver', 
         'JDBOR|@version', 
         'JDBOR|Availability|Licence|FullName', 
         'JDBOR|Availability|Licence|LegalCode', 
         'JDBOR|Availability|Licence|ShortIdentifier'], 
        axis = 1, inplace = True)

#Drop columns which were just stating English was the language used
df.drop(['JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name|@lang', 
         'JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name|@lang', 
         'JDBOR|DisorderList|Disorder|DisorderGroup|Name|@lang', 
         'JDBOR|DisorderList|Disorder|DisorderType|Name|@lang', 
         'JDBOR|DisorderList|Disorder|ExpertLink|@lang', 
         'JDBOR|DisorderList|Disorder|Name|@lang', 
         'JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name|@lang'], 
        axis = 1, inplace = True)

df.head()

,JDBOR|DisorderList|@count,JDBOR|DisorderList|Disorder|@id,JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|@count,JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|@id,JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name,JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|@count,JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|@id,JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name,JDBOR|DisorderList|Disorder|DisorderGroup|@id,JDBOR|DisorderList|Disorder|DisorderGroup|Name,JDBOR|DisorderList|Disorder|DisorderType|@id,JDBOR|DisorderList|Disorder|DisorderType|Name,JDBOR|DisorderList|Disorder|ExpertLink,JDBOR|DisorderList|Disorder|Name,JDBOR|DisorderList|Disorder|OrphaCode,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name
0,6636,44,2,23627,adult,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,Turner syndrome,881,2,23494,Not applicable
1,6636,44,2,23627,adult,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,Turner syndrome,881,2,23480,Unknown
2,6636,44,2,23634,elderly,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,Turner syndrome,881,2,23494,Not applicable
3,6636,44,2,23634,elderly,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,Turner syndrome,881,2,23480,Unknown
4,6636,44,2,23627,adult,4,23529,Childhood,36547,Disorder,21401,Malformation syndrome,http://www.orpha.net/consor/cgi-bin/OC_Exp.php...,Turner syndrome,881,2,23494,Not applicable

In [8]:
#Check how many columns are left now
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14591 entries, 0 to 14590
Data columns (total 18 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   JDBOR|DisorderList|@count                                                 14591 non-null  object
 1   JDBOR|DisorderList|Disorder|@id                                           14591 non-null  object
 2   JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|@count                  14591 non-null  object
 3   JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|@id   9312 non-null   object
 4   JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name  9312 non-null   object
 5   JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|@count                  14591 non-null  object
 6   JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|@id   14139 non-null  object
 7   JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name  14139 non-null  object
 8   JDBOR|DisorderList|Disorder|DisorderGroup|@id                             14591 non-null  object
 9   JDBOR|DisorderList|Disorder|DisorderGroup|Name                            14591 non-null  object
 10  JDBOR|DisorderList|Disorder|DisorderType|@id                              14591 non-null  object
 11  JDBOR|DisorderList|Disorder|DisorderType|Name                             14591 non-null  object
 12  JDBOR|DisorderList|Disorder|ExpertLink                                    14591 non-null  object
 13  JDBOR|DisorderList|Disorder|Name                                          14591 non-null  object
 14  JDBOR|DisorderList|Disorder|OrphaCode                                     14591 non-null  object
 15  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count                  14591 non-null  object
 16  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id   12433 non-null  object
 17  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name  12433 non-null  object
dtypes: object(18)
memory usage: 2.0+ MB

In [9]:
#Check what this column contains
df['JDBOR|DisorderList|Disorder|ExpertLink'].unique()

array(['http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=881',
       'http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=550',
       'http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=480',
       ...,
       'http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=99931',
       'http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=99932',
       'http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=1818'],
      dtype=object)

In [10]:
#Drop this column which is referring to links of information from Orphanet for rare diseases only
df.drop(columns = ['JDBOR|DisorderList|Disorder|ExpertLink'], inplace = True)
df.head()

,JDBOR|DisorderList|@count,JDBOR|DisorderList|Disorder|@id,JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|@count,JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|@id,JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name,JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|@count,JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|@id,JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name,JDBOR|DisorderList|Disorder|DisorderGroup|@id,JDBOR|DisorderList|Disorder|DisorderGroup|Name,JDBOR|DisorderList|Disorder|DisorderType|@id,JDBOR|DisorderList|Disorder|DisorderType|Name,JDBOR|DisorderList|Disorder|Name,JDBOR|DisorderList|Disorder|OrphaCode,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id,JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name
0,6636,44,2,23627,adult,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
1,6636,44,2,23627,adult,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown
2,6636,44,2,23634,elderly,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
3,6636,44,2,23634,elderly,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown
4,6636,44,2,23627,adult,4,23529,Childhood,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable

In [11]:
#Check how many columns left after removing several before
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14591 entries, 0 to 14590
Data columns (total 17 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   JDBOR|DisorderList|@count                                                 14591 non-null  object
 1   JDBOR|DisorderList|Disorder|@id                                           14591 non-null  object
 2   JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|@count                  14591 non-null  object
 3   JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|@id   9312 non-null   object
 4   JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name  9312 non-null   object
 5   JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|@count                  14591 non-null  object
 6   JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|@id   14139 non-null  object
 7   JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name  14139 non-null  object
 8   JDBOR|DisorderList|Disorder|DisorderGroup|@id                             14591 non-null  object
 9   JDBOR|DisorderList|Disorder|DisorderGroup|Name                            14591 non-null  object
 10  JDBOR|DisorderList|Disorder|DisorderType|@id                              14591 non-null  object
 11  JDBOR|DisorderList|Disorder|DisorderType|Name                             14591 non-null  object
 12  JDBOR|DisorderList|Disorder|Name                                          14591 non-null  object
 13  JDBOR|DisorderList|Disorder|OrphaCode                                     14591 non-null  object
 14  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count                  14591 non-null  object
 15  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id   12433 non-null  object
 16  JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name  12433 non-null  object
dtypes: object(17)
memory usage: 1.9+ MB

In [12]:
#Rename all columns for ease of reading
df.rename(columns = {'JDBOR|DisorderList|@count': 'Disorder list counts', 
                     'JDBOR|DisorderList|Disorder|@id': 'Disorder ID', 
                     'JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|@count': 'Average age of death - counts', 
                     'JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|@id': 'Average age of death ID', 
                     'JDBOR|DisorderList|Disorder|AverageAgeOfDeathList|AverageAgeOfDeath|Name': 'Average age of death', 
                     'JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|@count': 'Average age of onset counts', 
                     'JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|@id': 'Average age of onset ID', 
                     'JDBOR|DisorderList|Disorder|AverageAgeOfOnsetList|AverageAgeOfOnset|Name': 'Average age of onset', 
                     'JDBOR|DisorderList|Disorder|DisorderGroup|@id': 'Disorder group ID', 
                     'JDBOR|DisorderList|Disorder|DisorderGroup|Name': 'Disorder group name', 
                     'JDBOR|DisorderList|Disorder|DisorderType|@id': 'Disorder type ID', 
                     'JDBOR|DisorderList|Disorder|DisorderType|Name': 'Disorder type', 
                     'JDBOR|DisorderList|Disorder|Name': 'Disorder name', 
                     'JDBOR|DisorderList|Disorder|OrphaCode': 'Orpha code', 
                     'JDBOR|DisorderList|Disorder|TypeOfInheritanceList|@count': 'Type of inheritance list counts', 
                     'JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|@id': 'Type of inheritance ID', 
                     'JDBOR|DisorderList|Disorder|TypeOfInheritanceList|TypeOfInheritance|Name': 'Type of inheritance'}, 
         inplace = True)

df.head(10)

,Disorder list counts,Disorder ID,Average age of death - counts,Average age of death ID,Average age of death,Average age of onset counts,Average age of onset ID,Average age of onset,Disorder group ID,Disorder group name,Disorder type ID,Disorder type,Disorder name,Orpha code,Type of inheritance list counts,Type of inheritance ID,Type of inheritance
0,6636,44,2,23627,adult,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
1,6636,44,2,23627,adult,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown
2,6636,44,2,23634,elderly,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
3,6636,44,2,23634,elderly,4,23508,Antenatal,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown
4,6636,44,2,23627,adult,4,23529,Childhood,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
5,6636,44,2,23627,adult,4,23529,Childhood,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown
6,6636,44,2,23634,elderly,4,23529,Childhood,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
7,6636,44,2,23634,elderly,4,23529,Childhood,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown
8,6636,44,2,23627,adult,4,23522,Infancy,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23494,Not applicable
9,6636,44,2,23627,adult,4,23522,Infancy,36547,Disorder,21401,Malformation syndrome,Turner syndrome,881,2,23480,Unknown

In [13]:
#To see all types of rare diseases listed
df['Disorder type'].unique()

array(['Malformation syndrome', 'Disease', 'Clinical group',
       'Clinical subtype', 'Category', 'Morphological anomaly',
       'Clinical syndrome', 'Etiological subtype', 'Biological anomaly',
       'Particular clinical situation in a disease or syndrome',
       'Histopathological subtype'], dtype=object)

In [14]:
#Count the number of unique rare disease names in total
df['Disorder name'].nunique()

6636

In [15]:
#To show names of rare diseases (not shown in full as there are in total about 6636 different rare diseases)
df['Disorder name'].unique()

array(['Turner syndrome', 'MELAS', 'Kearns-Sayre syndrome', ...,
       'Idiopathic pulmonary hemosiderosis', 'Heiner syndrome',
       'Ectodermal dysplasia, trichoodontoonychial type'], dtype=object)

In [16]:
#Show the types of inheritance for the rare diseases
df['Type of inheritance'].unique()

array(['Not applicable', 'Unknown', 'Mitochondrial inheritance',
       'Autosomal recessive', 'X-linked dominant', 'X-linked recessive',
       'Autosomal dominant', 'Multigenic/multifactorial', 'Oligogenic',
       'Y-linked', 'Semi-dominant', 'No data available', nan],
      dtype=object)

In [17]:
#Create another dataframe with columns: disorder type, disorder name, type of inheritance, 
#average age of onset, average age of death
rd = df[['Disorder type', 'Disorder name', 'Type of inheritance', 'Average age of onset', 'Average age of onset counts', 'Average age of death', 'Average age of death - counts']].copy()
rd.head()

,Disorder type,Disorder name,Type of inheritance,Average age of onset,Average age of onset counts,Average age of death,Average age of death - counts
0,Malformation syndrome,Turner syndrome,Not applicable,Antenatal,4,adult,2
1,Malformation syndrome,Turner syndrome,Unknown,Antenatal,4,adult,2
2,Malformation syndrome,Turner syndrome,Not applicable,Antenatal,4,elderly,2
3,Malformation syndrome,Turner syndrome,Unknown,Antenatal,4,elderly,2
4,Malformation syndrome,Turner syndrome,Not applicable,Childhood,4,adult,2

In [18]:
#To see all different average age of deaths present in data
rd['Average age of death'].unique()

array(['adult', 'elderly', 'adolescent', 'late childhood', 'young Adult',
       'normal life expectancy', 'early childhood', 'infantile',
       'embryofetal', 'stillbirth', 'any age', 'No data available',
       'Not yet documented', nan], dtype=object)

In [19]:
#Observe frequencies of all the categories of average age of death
rd['Average age of death'].value_counts()

No data available         2264
normal life expectancy    2245
any age                    893
adult                      725
infantile                  721
early childhood            680
elderly                    427
late childhood             423
adolescent                 333
young Adult                281
stillbirth                 230
embryofetal                 83
Not yet documented           7
Name: Average age of death, dtype: int64

In [20]:
#Observe frequencies of all the categories of average age of onset
rd['Average age of onset'].value_counts()

Neonatal             3850
Infancy              3081
Childhood            1989
Adult                1708
Antenatal            1035
All ages             1031
Adolescent           1000
Elderly               402
No data available      43
Name: Average age of onset, dtype: int64

In [21]:
#Create a filter to find out rare disease disorder type of malformation syndrome only
#with average age of onset as antenatal and average age of death as elderly
selection_mal_syn = (rd['Disorder type'] == 'Malformation syndrome') & (rd['Average age of onset'] == 'Antenatal') & (rd['Average age of death'] == 'elderly')
print(selection_mal_syn)

0        False
1        False
2         True
3         True
4        False
         ...
14586    False
14587    False
14588    False
14589    False
14590    False
Length: 14591, dtype: bool

In [22]:
#apply the filter to the dataset rd
a = rd[selection_mal_syn]
a

,Disorder type,Disorder name,Type of inheritance,Average age of onset,Average age of onset counts,Average age of death,Average age of death - counts
2,Malformation syndrome,Turner syndrome,Not applicable,Antenatal,4,elderly,2
3,Malformation syndrome,Turner syndrome,Unknown,Antenatal,4,elderly,2
357,Malformation syndrome,Prune belly syndrome,Autosomal dominant,Antenatal,2,elderly,3
358,Malformation syndrome,Prune belly syndrome,Not applicable,Antenatal,2,elderly,3
359,Malformation syndrome,Prune belly syndrome,X-linked recessive,Antenatal,2,elderly,3

In [23]:
#List the unique disorder name after applying this filter
a['Disorder name'].unique()

array(['Turner syndrome', 'Prune belly syndrome'], dtype=object)

It turns out that Turner syndrome and Prune belly syndrome are the only two disorders of the malformation syndrome type that have an average age of onset at antenatal period with an average age of death in elderly years. This means these two rare disorders have had relatively long life spans out of all the rare diseases present in the dataset.

In [24]:
#To find out the rare diseases that have the same time of onsets but with earlier deaths than elderly years
#One of the examples
selection_mal_syn_early = (rd['Disorder type'] == 'Malformation syndrome') & (rd['Average age of onset'] == 'Antenatal') & (rd['Average age of death'] == 'early childhood')
b = rd[selection_mal_syn_early]
b

,Disorder type,Disorder name,Type of inheritance,Average age of onset,Average age of onset counts,Average age of death,Average age of death - counts
172,Malformation syndrome,Noonan syndrome,Autosomal dominant,Antenatal,4,early childhood,5
173,Malformation syndrome,Noonan syndrome,Autosomal recessive,Antenatal,4,early childhood,5
226,Malformation syndrome,Trisomy 13,Not applicable,Antenatal,2,early childhood,2
227,Malformation syndrome,Trisomy 13,Unknown,Antenatal,2,early childhood,2
448,Malformation syndrome,Hydranencephaly,Autosomal recessive,Antenatal,2,early childhood,6
449,Malformation syndrome,Hydranencephaly,Unknown,Antenatal,2,early childhood,6
494,Malformation syndrome,3C syndrome,Autosomal recessive,Antenatal,3,early childhood,2
495,Malformation syndrome,3C syndrome,X-linked recessive,Antenatal,3,early childhood,2
506,Malformation syndrome,Antley-Bixler syndrome,Autosomal dominant,Antenatal,2,early childhood,5
507,Malformation syndrome,Antley-Bixler syndrome,Autosomal recessive,Antenatal,2,early childhood,5
572,Malformation syndrome,Matthew-Wood syndrome,Autosomal dominant,Antenatal,2,early childhood,3
573,Malformation syndrome,Matthew-Wood syndrome,Autosomal recessive,Antenatal,2,early childhood,3
904,Malformation syndrome,Trisomy 18,Not applicable,Antenatal,2,early childhood,1
905,Malformation syndrome,Trisomy 18,Unknown,Antenatal,2,early childhood,1
948,Malformation syndrome,Tetrasomy 12p,Not applicable,Antenatal,2,early childhood,1
949,Malformation syndrome,Tetrasomy 12p,Unknown,Antenatal,2,early childhood,1
1133,Malformation syndrome,C syndrome,Not applicable,Antenatal,2,early childhood,1
1134,Malformation syndrome,C syndrome,Unknown,Antenatal,2,early childhood,1
2479,Malformation syndrome,Cat-eye syndrome,Not applicable,Antenatal,2,early childhood,2
2788,Malformation syndrome,Bartsocas-Papas syndrome,Autosomal recessive,Antenatal,2,early childhood,2
2792,Malformation syndrome,Bowen-Conradi syndrome,Autosomal recessive,Antenatal,2,early childhood,4
2824,Malformation syndrome,Cortical blindness-intellectual disability-pol...,Autosomal recessive,Antenatal,2,early childhood,2
2872,Malformation syndrome,Vici syndrome,Autosomal recessive,Antenatal,2,early childhood,4
2894,Malformation syndrome,Fryns syndrome,Autosomal recessive,Antenatal,2,early childhood,4
3042,Malformation syndrome,Acromelic frontonasal dysplasia,Autosomal dominant,Antenatal,2,early childhood,2
3048,Malformation syndrome,Wiedemann-Rautenstrauch syndrome,Autosomal recessive,Antenatal,2,early childhood,7
3078,Malformation syndrome,Müllerian derivatives-lymphangiectasia-polydac...,Unknown,Antenatal,2,early childhood,2
3270,Malformation syndrome,Craniofacial dysplasia-short stature-ectoderma...,Autosomal recessive,Antenatal,2,early childhood,2
3326,Malformation syndrome,Autosomal dominant myopia-midfacial retrusion-...,Autosomal dominant,Antenatal,2,early childhood,2
3497,Malformation syndrome,Timothy syndrome,Autosomal dominant,Antenatal,2,early childhood,3
3531,Malformation syndrome,Rhombencephalosynapsis,Not applicable,Antenatal,3,early childhood,3
3762,Malformation syndrome,MEHMO syndrome,X-linked recessive,Antenatal,3,early childhood,2
3804,Malformation syndrome,Bohring-Opitz syndrome,Autosomal dominant,Antenatal,2,early childhood,5
3926,Malformation syndrome,Pontocerebellar hypoplasia type 4,Autosomal recessive,Antenatal,1,early childhood,2
3970,Malformation syndrome,Joubert syndrome,Autosomal recessive,Antenatal,1,early childhood,2
4061,Malformation syndrome,Autosomal recessive spondylometaphyseal dyspla...,Autosomal recessive,Antenatal,1,early childhood,2
4393,Malformation syndrome,Microcephaly-polymicrogyria-corpus callosum ag...,Autosomal recessive,Antenatal,2,early childhood,1
4687,Malformation syndrome,Cranioectodermal dysplasia,Autosomal recessive,Antenatal,2,early childhood,1
4689,Malformation syndrome,Epiphyseal stippling-osteoclastic hyperplasia ...,Autosomal recessive,Antenatal,2,early childhood,1
4786,Malformation syndrome,Hydrolethalus,Autosomal recessive,Antenatal,2,early childhood,1
12449,Malformation syndrome,Mosaic trisomy 17,NaN,Antenatal,2,early childhood,4
12471,Malformation syndrome,Proximal Xq28 duplication syndrome,NaN,Antenatal,2,early childhood,6

In [25]:
b['Disorder name'].unique()

array(['Noonan syndrome', 'Trisomy 13', 'Hydranencephaly', '3C syndrome',
       'Antley-Bixler syndrome', 'Matthew-Wood syndrome', 'Trisomy 18',
       'Tetrasomy 12p', 'C syndrome', 'Cat-eye syndrome',
       'Bartsocas-Papas syndrome', 'Bowen-Conradi syndrome',
       'Cortical blindness-intellectual disability-polydactyly syndrome',
       'Vici syndrome', 'Fryns syndrome',
       'Acromelic frontonasal dysplasia',
       'Wiedemann-Rautenstrauch syndrome',
       'Müllerian derivatives-lymphangiectasia-polydactyly syndrome',
       'Craniofacial dysplasia-short stature-ectodermal anomalies-intellectual disability syndrome',
       'Autosomal dominant myopia-midfacial retrusion-sensorineural hearing loss-rhizomelic dysplasia syndrome',
       'Timothy syndrome', 'Rhombencephalosynapsis', 'MEHMO syndrome',
       'Bohring-Opitz syndrome', 'Pontocerebellar hypoplasia type 4',
       'Joubert syndrome',
       'Autosomal recessive spondylometaphyseal dysplasia, Mégarbané type',
       'Microcephaly-polymicrogyria-corpus callosum agenesis syndrome',
       'Cranioectodermal dysplasia',
       'Epiphyseal stippling-osteoclastic hyperplasia syndrome',
       'Hydrolethalus', 'Mosaic trisomy 17',
       'Proximal Xq28 duplication syndrome'], dtype=object)

Oppositely, there are far more rare disorders (as shown above) with early childhood deaths within the malformation syndrome type, while having the same antenatal onsets as Turner syndrome and Prune belly syndrome.